### ISSUE TITLE
[1.14.4] messages in config always get resets to default on reboot

### ISSUE THREAD

**Issue by mdylantk** [LotuxPunk/AutoMessageDisplayerForge#3]
I hope you find time to look into this issue. The settings before and after messages section do not get reset, only the messages.

I tried replacing the words within the Quotation marks as well as keeping the first two messages and adding more. It should be simple to recreate, if not, then feel free to close this message.

**Comment by LotuxPunk** [comment]
Hey!
Could you send me your configuration file ?

I don’t really understand your issue 😅

**Comment by mdylantk** [comment]
line 11 on server start or world load on single player it gets change to `messages = ["Thanks for downloading AutoMessageDisplayer", "Cake or pie ?"]`  so there no way for me to add new messages. 

[https://gist.github.com/mdylantk/1c7def24ecbab38a8cd228a4789e05cc](url)

**Comment by ProsperCraft** [comment]
What happens if you shut down, change the config, then start up?

We have had this problem with bukkit plugins in the past, you had to edit them while the server was off because they saved out their config fo no reason with data that it had loaded on server load.

**Comment by ProsperCraft** [comment]
We have been arguing about pie vs cake for a while now :)

**Comment by LotuxPunk** [comment]
Ahaha, I'm so sorry 😅

**Comment by LotuxPunk** [comment]
Ok, it's fixed !
