### ISSUE TITLE
[1.14.4] Please update to forge .45 it has breaking changes.

### ISSUE THREAD

**Issue by ProsperCraft** [LotuxPunk/AutoMessageDisplayerForge#5]
I updated https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk to forge .45 but had to leave behind several mods because they won't load due to breaking changes, please update to .45 so I can add it back in.

**Comment by Jeryn99** [comment]
As a note of reference for Lotux: 
https://twitter.com/LexManos/status/1158426171500924930?s=09

**Comment by LotuxPunk** [comment]
Thanks, I’ll look at it !

**Comment by LotuxPunk** [comment]
Should work now : https://www.curseforge.com/minecraft/mc-mods/automessagedisplayer/files/2760294
